<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.0-beta1 setup script
 * Date: Sat, 28 Jan 2012 02:49:17 +0100
 */

$i = 0;


$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['hide_db'] = '^(performance_schema|information_schema|mysql)$';

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['blowfish_secret'] = 'xda';
$cfg['LoginCookieStore'] = 604800;
$cfg['QueryHistoryDB'] = false;
$cfg['QueryHistoryMax'] = 100;
$cfg['RetainQueryBox'] = true;
$cfg['LeftDisplayServers'] = true;
$cfg['LeftFrameDBTree'] = false;
$cfg['ShowPhpInfo'] = true;
$cfg['ShowAll'] = true;
$cfg['LoginCookieValidity'] = 60 * 60 * 24*7;
ini_set('session.gc_maxlifetime', $cfg['LoginCookieValidity']);

# Show 150 rows instead of 30 by default
$cfg['MaxRows'] = 150;
# Show BLOB data as a string not hex.
$cfg['DisplayBinaryAsHex'] = false;
# Show BLOB data in row detail pages.
$cfg['ProtectBinary'] = false;
# Show BLOB data on table browse pages.  Hack to hardcode all requests.
$_REQUEST['display_blob'] = true;